services:
  server:
    build: ./server
    env_file: "./server/.env"
    depends_on:
      - postgres
      - test-postgres
    ports:
      - "3000:3000"
    networks:
      - postgres-network
    volumes:
      - ./server:/server

  client:
    build: ./client
    env_file: "./client/.env"
    depends_on:
      - server
    network_mode: host
    volumes:
      - ./client:/client

  postgres:
    image: postgres:13.5
    restart: always
    env_file: "./server/.env"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  test-postgres:
    image: postgres:13.5
    restart: always
    env_file: "./server/.env.test"
    volumes:
      - test-postgres:/var/lib/postgresql/test-data
    ports:
      - "5435:5435"
    networks:
      - postgres-network

volumes:
  postgres:
  test-postgres:

networks:
  postgres-network:
