services:
  server:
    build: ./server
    env_file: "./server/.env"
    depends_on:
      - postgres
      - test-postgres
    command: sh -c "npx prisma db push && npm run start:dev"
    ports:
      - "3000:3000"
    networks:
      - postgres-network
    volumes:
      - ./server:/server
      - /server/node_modules

  client:
    build: ./client
    depends_on:
      - server
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client
      - /client/node_modules

  postgres:
    image: postgres:13.5
    restart: always
    env_file: "./server/.env"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  test-postgres:
    image: postgres:13.5
    restart: always
    env_file: "./server/.env.test"
    volumes:
      - test-postgres:/var/lib/postgresql/test-data
    ports:
      - "5435:5435"
    networks:
      - postgres-network

volumes:
  postgres:
  test-postgres:

networks:
  postgres-network:
