const REFRESH_TOKEN_EXPIRES_IN = '7d';
const ACCESS_TOKEN_EXPIRES_IN = '15m';
const REFRESH_TOKEN_EXPIRES_IN_SECONDS = 7 * 24 * 60 * 60;
const REFRESH_TOKEN_EXPIRES_IN_MILLISECONDS =
  REFRESH_TOKEN_EXPIRES_IN_SECONDS * 1000;

export {
  REFRESH_TOKEN_EXPIRES_IN_SECONDS,
  REFRESH_TOKEN_EXPIRES_IN,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_EXPIRES_IN_MILLISECONDS,
};
